### PR TITLE
Allow passing env variable in path parameters

### PR DESCRIPTION
**Pull request by liushuya7**
This modification will allow users to either pass in an absolute path or path with environment variables if they are set.

### CODE REVIEW

**Comment by htp2** [comment]
I'm having trouble understanding why the env var is not evaluated in the commandline or bash script. When I do that, I get this behavior.

Does it actually pass the string with the $ in for you?

For me, things work just fine if I do e.g.
``` bash
/home/$USER/ambf/bin/lin-x86_64/ambf_simulator --plugins $CATKIN_WS/build/ambf_trace_plugin/libambf_trace_plugin.so --csv_filename_static_trace $CATKIN_WS/src/continuum-manip-volumetric-drilling-plugin/resources/axis.csv 
```

**Comment by liushuya7** [comment]
Oh, so it works on yours? Somehow it passes the string with the $ for me.

**Comment by htp2** [comment]
Can you print the output of 
```bash 
printenv | grep CATKIN
```

**Comment by liushuya7** [comment]
It works on mine as well. Please ignore this PR.

**Comment by htp2** [comment]
Glad it's working!

**Pull request closed without merging**
